{% set name = "App-cpanminus" %}
{% set version = "1.7044" %}
{% set sha256 = "9b60767fe40752ef7a9d3f13f19060a63389a5c23acc3e9827e19b75500f81f3" %}

package:
  name: perl-{{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 1
  skip: True  # [win]

requirements:
  host:
    - perl
  run:
    - perl 

test:
  commands:
    - cpanm --help 2>&1 | grep 'Usage' 

about:
  home: https://metacpan.org/pod/App::cpanminus
  license: perl 
  license_family: MIT
  license_file: LICENSE
  summary: 'get, unpack build and install modules from CPAN'

  description: |
    cpanminus is a script to get, unpack, build and install modules from CPAN
    and does nothing else.

    It's dependency free (can bootstrap itself), requires zero configuration,
    and stands alone. When running, it requires only 10MB of RAM.
  doc_url: https://metacpan.org/release/MIYAGAWA/App-cpanminus-1.7043
  dev_url: https://github.com/miyagawa/cpanminus.git

extra:
  recipe-maintainers:
    - jerowe 
