{% set version = "1.7043" %}
{% set sha256 = "68a06f7da80882a95bc02c92c7ee305846fb6ab648cf83678ea945e44ad65c65" %}

package:
  name: perl-app-cpanminus
  version: {{ version }}

source:
  url: https://cpan.metacpan.org/authors/id/M/MI/MIYAGAWA/App-cpanminus-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 2
  noarch: generic
  script:
    - perl Makefile.PL INSTALLDIRS=vendor NO_PERLLOCAL=1 NO_PACKLIST=1
    - make
    - make test
    - make install VERBINST=1

requirements:
  build:
    - make
  host:
    - perl
  run:
    - perl 

test:
  commands:
    - cpanm --help 2>&1 | grep 'Usage' 

about:
  home: https://metacpan.org/pod/App::cpanminus
  license: GPL-1.0-or-later OR Artistic-1.0-Perl
  license_file: LICENSE
  summary: 'get, unpack build and install modules from CPAN'

  description: |
    cpanminus is a script to get, unpack, build and install modules from CPAN
    and does nothing else.

    It's dependency free (can bootstrap itself), requires zero configuration,
    and stands alone. When running, it requires only 10MB of RAM.
  doc_url: https://metacpan.org/release/MIYAGAWA/App-cpanminus-1.7043
  dev_url: https://github.com/miyagawa/cpanminus.git

extra:
  recipe-maintainers:
    - jerowe 
