# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "IqgMz0+Zt2+TV/8Ku4HmlHKTl4qo/6qioYgLAMAQkYP18TnfKHwnTICilGejqqYOadb6A1dxf1+K1P/CJmmr14fgoJtLj4naPm8TeHTpch88Tj/vGbMPocnBl/Pq5em7wpQucY//cITcNo03ccFNBROY46aEEuFeY2eEdDtXDARANWaU80aLI2vwMKAATPqPCt8PpnGyy0TaeWZZ85qu9z8o4H5DC81BvL+tWhiqM7sdwMjpL8eMYvZwFyahn5q18cndD0Xh2k8TfF77nKxRLS7PdkeHefzmP2RwMGzKMlmX0mIn3QiTaVjflMgwIWNg3/J9uKToi9kv+xEUV5xQtG+N5MVzEm/nYSbcRO/AZIQDMdREk3h7PhOvaBVb+1q4ZK6id0++cNjZMKkbZSMWiOhnrqJ4us+3+GHqYil3rKPy8hEZtVtxZglAeqHZC20ZWYPKI6yi6rC4T9u1gaplYBSawvLnw4PTfg6JXqNIgM6fXYAy07P7mkFs3OYegoiJBh0yTd9IgArb/mcaTpDr2ce7tKLnP5IZo4cIfDRXLrq3Pwo4V7oIRvNWYDS2qQLg8tcjQmpfJSykMWW5anAr2ImqDtnaHVuHcfmQKvD1cAjDWASq8y9Ky2ttLrnShPmHq9pik47REH+YqR4eoAPWO2M9XTbMiUnBMd9wrQVkY5U="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-ci-setup=1
      source run_conda_forge_build_setup

script:
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml

  - upload_or_check_non_existence ./recipe conda-forge --channel=main -m ./.ci_support/${CONFIG}.yaml
