travis:
  secure:
    BINSTAR_TOKEN: UWUfe39KXmDeX94Ebnvs3gwuRnYvcSaInW56ABsZW3HHOhcvlYY6RifD63uLdh9Z+SZYVEXvzQ1lY2BdXjTYcYo094bSaWMLBAXgEL1C4n28xhckD6WmqOQW/2c9n4RLADvwGPeK9kRMxkJYIaiG6HE0HngYQccphXKiweEEJ5uL16ETC1xITdJROu+R7f/K7nfTO+8xKZxZkxGP3oxNRA6SJykhJsPhPbCo2goDRBHnweRRdNqqb1L+LaR0i2cosBQSIhJFSoh04VhvrKXwsRQapVpAWXmOpbedjgPaSVt0d7Auci4u8+Jdp1yS8tHKvlm+RrKaiXt6MYptBfB+WsvhKU+Evi3w30fjSxoxg3NLWKBJr8laIMUnhls9h+igwuoFPGMlQxLOFfbbnaop3hwPrcxiEpcADqmbouD5UvOvXQD1h3KwlfVChA+i83ARZLU5x/MpIus2QCfxFKgtcyOqM7GL8YsrbyH00GNvQ2sOSRzMXyqsvYFEGi7J3dG7VMmMcDnSHBrUt06bYimn2iIvuB8dIIUHJY3zRiZjbhb9nBdPId0DiwRF70ilHXeAy9/PugkxEwdswei7pZBF5wZ9aEIcssOUv5TVCHM5ailDv0w65CMRiWeSOuGHTrnCGMlFJIlFZrU+pR3cZE+/e7mMfD1mzl1zYszJZhCdHjE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
conda_forge_output_validation: true
