travis:
  secure:
    BINSTAR_TOKEN: IqgMz0+Zt2+TV/8Ku4HmlHKTl4qo/6qioYgLAMAQkYP18TnfKHwnTICilGejqqYOadb6A1dxf1+K1P/CJmmr14fgoJtLj4naPm8TeHTpch88Tj/vGbMPocnBl/Pq5em7wpQucY//cITcNo03ccFNBROY46aEEuFeY2eEdDtXDARANWaU80aLI2vwMKAATPqPCt8PpnGyy0TaeWZZ85qu9z8o4H5DC81BvL+tWhiqM7sdwMjpL8eMYvZwFyahn5q18cndD0Xh2k8TfF77nKxRLS7PdkeHefzmP2RwMGzKMlmX0mIn3QiTaVjflMgwIWNg3/J9uKToi9kv+xEUV5xQtG+N5MVzEm/nYSbcRO/AZIQDMdREk3h7PhOvaBVb+1q4ZK6id0++cNjZMKkbZSMWiOhnrqJ4us+3+GHqYil3rKPy8hEZtVtxZglAeqHZC20ZWYPKI6yi6rC4T9u1gaplYBSawvLnw4PTfg6JXqNIgM6fXYAy07P7mkFs3OYegoiJBh0yTd9IgArb/mcaTpDr2ce7tKLnP5IZo4cIfDRXLrq3Pwo4V7oIRvNWYDS2qQLg8tcjQmpfJSykMWW5anAr2ImqDtnaHVuHcfmQKvD1cAjDWASq8y9Ky2ttLrnShPmHq9pik47REH+YqR4eoAPWO2M9XTbMiUnBMd9wrQVkY5U=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
